# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Bird sound prediction")
        Dialog.resize(1071, 817)
        Dialog.setStyleSheet("font: 10pt \"楷体\";")
        self.upload = QtWidgets.QPushButton(Dialog)
        self.upload.setGeometry(QtCore.QRect(30, 120, 191, 71))
        self.upload.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(125, 125, 125, 255), stop:1 rgba(255, 255, 255, 255));\n"
            "font: 12pt \"楷体\";\n"
            "")
        self.upload.setObjectName("upload")
        self.recording = QtWidgets.QPushButton(Dialog)
        self.recording.setGeometry(QtCore.QRect(250, 120, 191, 71))
        self.recording.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(125, 125, 125, 255), stop:1 rgba(255, 255, 255, 255));\n"
            "font: 12pt \"楷体\";")
        self.recording.setObjectName("recording")
        self.test = QtWidgets.QPushButton(Dialog)
        self.test.setGeometry(QtCore.QRect(140, 240, 191, 71))
        self.test.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(125, 125, 125, 255), stop:1 rgba(255, 255, 255, 255));\n"
            "font: 12pt \"楷体\";")
        self.test.setMouseTracking(False)
        self.test.setObjectName("test")

        self.reset = QtWidgets.QPushButton(Dialog)
        self.reset.setGeometry(QtCore.QRect(140, 340, 191, 71))
        self.reset.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(125, 125, 125, 255), stop:1 rgba(255, 255, 255, 255));\n"
            "font: 12pt \"楷体\";")
        self.reset.setObjectName("reset_button")
        #self.reset.setObjectName("reset")

        self.sound = QtWidgets.QGraphicsView(Dialog)
        self.sound.setGeometry(QtCore.QRect(560, 60, 491, 201))
        self.sound.setObjectName("sound")
        self.mfcc = QtWidgets.QGraphicsView(Dialog)
        self.mfcc.setGeometry(QtCore.QRect(560, 300, 491, 201))
        self.mfcc.setObjectName("mfcc")
        self.Spec = QtWidgets.QGraphicsView(Dialog)
        self.Spec.setGeometry(QtCore.QRect(560, 550, 491, 201))
        self.Spec.setObjectName("Spec")
        self.birdimage = QtWidgets.QGraphicsView(Dialog)
        self.birdimage.setGeometry(QtCore.QRect(95, 540, 301, 241))
        self.birdimage.setObjectName("birdimage")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(70, 460, 351, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 410, 91, 71))
        self.label.setStyleSheet("font: 12pt \"楷体\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(560, 270, 81, 41))
        self.label_2.setStyleSheet("font: 12pt \"楷体\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(560, 510, 151, 61))
        self.label_3.setStyleSheet("font: 12pt \"楷体\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(560, 30, 81, 31))
        self.label_4.setStyleSheet("font: 12pt \"楷体\";")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(30, 70, 411, 31))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MainWindow"))
        self.upload.setText(_translate("Dialog", "上传音频"))
        self.recording.setText(_translate("Dialog", "录制音频"))
        self.test.setText(_translate("Dialog", "开始预测"))
        self.reset.setText(_translate("Dialog", "重新选择文件"))
        self.label.setText(_translate("Dialog", "预测结果"))
        self.label_2.setText(_translate("Dialog", "MFCC图"))
        self.label_3.setText(_translate("Dialog", "梅尔频谱图"))
        self.label_4.setText(_translate("Dialog", "波形图"))
